const fs = require('fs');

try {
    let content = fs.readFileSync('index.html', 'utf8');

    // Price and currency updates
    content = content.replace(/R\$\s*59,90/g, 'US$ 29.90');
    content = content.replace(/R\$\s*29,90/g, 'US$ 14.90');
    content = content.replace(/value:\s*27\.90/g, 'value: 14.90');
    content = content.replace(/'BRL'/g, "'USD'");
    content = content.replace(/"BRL"/g, '"USD"');

    const replacements = {
        'Paños de Cocina': 'Paños de Cocina',
        'em 1.943 avaliações': 'en 1.943 evaluaciones',
        'Transforme Seus Paños de Cocina': 'Transforma Tus Paños de Cocina',
        'Avaliação de 4,91 de 5 com 1.943 avaliações': 'Evaluación de 4.91 de 5 con 1.943 evaluaciones',
        'em Piezas Únicas Hechas por Ti': 'en Piezas Únicas Hechas por Ti',
        'com desenhos exclusivos, classe em vídeo passo a passo e bônus para tus primeiras peças.': 'con diseños exclusivos, clase en video paso a paso y bonos para tus primeras piezas.',
        'com diseños exclusivos, clase en video passo a passo e bono para tus primeiras peças.': 'con diseños exclusivos, clase en video paso a paso y bonos para tus primeras piezas.',
        'prontos para imprimir em tamanho real, transferir para o paño de cocina e empezar a pintar.': 'listos para imprimir en tamaño real, transferir al paño de cocina y empezar a pintar.',
        'acompanhe o passo a passo da pintura,': 'sigue el paso a paso de la pintura,',
        'do preparo ao acabamento, com explicações simples': 'desde la preparación hasta el acabado, con explicaciones simples',
        'para criar tus primeiras peças.': 'para crear tus primeras piezas.',
        'aprenda a transferir seus diseños para o paño de cocina com papel carbono, evitando desenhos tortos, falhas e marcas fora do lugar.': 'aprende a transferir tus diseños al paño de cocina con papel carbón, evitando dibujos torcidos, fallas y marcas fuera de lugar.',
        'receba sugestões de paletas harmoniosas para escolher tus tintas com mais facilidade e criar pinturas ainda mais bonitas.': 'recibe sugerencias de paletas armoniosas para elegir tus pinturas con más facilidad y crear pinturas aún más bonitas.',
        'aprenda como calcular preços, montar kits, divulgar seus trabalhos e conquistar seus primeiros clientes.': 'aprende cómo calcular precios, armar kits, divulgar tus trabajos y conquistar tus primeros clientes.',
        'E estes são apenas alguns dos modelos que tú vai receber.': 'Y estos son solo algunos de los modelos que recibirás.',
        'Dentro da coleção tú encontra diseños de:': 'Dentro de la colección encontrarás diseños de:',
        'Simples e rápido': 'Simple y rápido',
        'Agora veja como é simples passar qualquer diseño para o': 'Ahora mira qué simple es pasar cualquier diseño al',
        'Tú não precisa saber desenhar. Depois de imprimir o modelo,': 'No necesitas saber dibujar. Después de imprimir el modelo,',
        'basta usar papel carbono para passar as linhas ao paño antes de começar a pintura.': 'solo usa papel carbón para pasar las líneas al paño antes de comenzar a pintar.',
        'Imprima o diseño': 'Imprime el diseño',
        'Escolha um dos 120 modelos e imprima o desenho': 'Elige uno de los 120 modelos e imprime el diseño',
        'em uma folha A4.': 'en una hoja A4.',
        'Posicione o papel carbono': 'Posiciona el papel carbón',
        'Coloque o papel carbono sobre o paño, com o lado que transfere a marca voltado': 'Coloca el papel carbón sobre el paño, con el lado que transfiere la marca hacia',
        'para o tecido.': 'la tela.',
        'Coloque o diseño por cima': 'Coloca el diseño por encima',
        'Posicione a folha impressa sobre o carbono e prenda': 'Posiciona la hoja impresa sobre el carbón y sujeta',
        'as extremidades para o desenho não sair do lugar.': 'las extremidades para que el diseño no se mueva de lugar.',
        'Contorne as linhas': 'Contornea las líneas',
        'Passe um lápis ou uma ponta firme sobre as linhas': 'Pasa un lápiz o una punta firme sobre las líneas',
        'do desenho para transferir o contorno ao paño.': 'del diseño para transferir el contorno al paño.',
        'Retire os papéis e pinte': 'Retira los papeles y pinta',
        'Retire a folha e o carbono. O desenho ficará marcado': 'Retira la hoja y el carbón. El diseño quedará marcado',
        'no tecido, pronto para receber a pintura.': 'en la tela, listo para recibir la pintura.',
        'O Guía de Transferencia está incluído na sua compra.': 'La Guía de Transferencia está incluida en tu compra.',
        'Tú receberá orientações para utilizar o papel carbono': 'Recibirás orientaciones para utilizar el papel carbón',
        'e transferir os diseños, mesmo que nunca tenha': 'y transferir los diseños, aunque nunca hayas',
        'feito esse processo antes.': 'hecho este proceso antes.',
        'Tú também recebe': 'También recibes',
        '4 bono exclusivos': '4 bonos exclusivos',
        'Materiais complementares para facilitar sua pintura,': 'Materiales complementarios para facilitar tu pintura,',
        'melhorar seus resultados e ajudar tú a começar': 'mejorar tus resultados y ayudarte a empezar',
        'com mais segurança.': 'con más seguridad.',
        'Todos os bono estão incluídos na coleção.': 'Todos los bonos están incluidos en la colección.',
        'Tú recebe os 120 diseños e os quatro materiais extras': 'Recibes los 120 diseños y los cuatro materiales extras',
        'sem pagar nada a mais.': 'sin pagar nada más.',
        'Pinturas de quem já começou': 'Pinturas de quienes ya empezaron',
        'Veja o que nossas clientes estão': 'Mira lo que nuestras clientas están',
        'Veja alguns trabalhos compartilhados por clientes': 'Mira algunos trabajos compartidos por clientas',
        'que já colocaram os diseños em prática.': 'que ya pusieron los diseños en práctica.',
        'Resultados compartilhados por clientes. A experiência e o acabamento': 'Resultados compartidos por clientas. La experiencia y el acabado',
        'podem variar de acordo com a prática e os materiais utilizados.': 'pueden variar según la práctica y los materiales utilizados.',
        'Tú tem 7 dias para': 'Tienes 7 días para',
        'avaliar o material': 'evaluar el material',
        'Compre hoje, acesse os arquivos e conheça os diseños e bono': 'Compra hoy, accede a los archivos y conoce los diseños y bonos',
        'incluídos na coleção. Caso o material não atenda às tus': 'incluidos en la colección. Si el material no cumple tus',
        'expectativas, tú poderá solicitar o reembolso dentro do': 'expectativas, podrás solicitar el reembolso dentro del',
        'prazo e das condições da garantia.': 'plazo y las condiciones de la garantía.',
        'Acesse os 120 diseños após a confirmação do pagamento.': 'Accede a los 120 diseños después de la confirmación del pago.',
        'Confira os arquivos e os quatro bono incluídos.': 'Revisa los archivos y los cuatro bonos incluidos.',
        'Avalie se o material atende ao que tú procura.': 'Evalúa si el material es lo que buscas.',
        'Solicite o reembolso dentro das condições da garantia.': 'Solicita el reembolso dentro de las condiciones de la garantía.',
        'Tenha acesso aos 120 diseños exclusivos,': 'Ten acceso a los 120 diseños exclusivos,',
        'à clase en video de pintura em tecido do zero': 'a la clase en video de pintura en tela desde cero',
        'e aos bono que vão facilitar tus primeiras peças.': 'y a los bonos que facilitarán tus primeras piezas.',
        'Quem criou esta coleção': 'Quién creó esta colección',
        'Uma paixão que se transformou': 'Una pasión que se transformó',
        'em inspiração para tú': 'en inspiración para ti',
        'Eu sou apaixonada por pintura em paño de cocina': 'Soy apasionada por la pintura en paños de cocina',
        'e sei como pode ser desafiador encontrar diseños': 'y sé lo desafiante que puede ser encontrar diseños',
        'bonitos, bem definidos e prontos para usar.': 'bonitos, bien definidos y listos para usar.',
        'Por isso, criei esta coleção com muito carinho,': 'Por eso, creé esta colección con mucho cariño,',
        'reunindo 120 diseños exclusivos, organizados por temas,': 'reuniendo 120 diseños exclusivos, organizados por temas,',
        'para que tú possa imprimir, transferir e começar': 'para que puedas imprimir, transferir y empezar',
        'a pintar sem perder tempo procurando modelos pela internet.': 'a pintar sin perder tiempo buscando modelos por internet.',
        'Cada desenho foi selecionado pensando em facilitar': 'Cada diseño fue seleccionado pensando en facilitar',
        'o seu dia a dia e ajudar tú a criar peças lindas,': 'tu día a día y ayudarte a crear piezas hermosas,',
        'seja para o seu prazer, para presentear ou até': 'ya sea por placer, para regalar o incluso',
        'para generar ingresos desde casa.': 'para generar ingresos desde casa.',
        'CRIADORA DA COLEÇÃO': 'CREADORA DE LA COLECCIÓN',
        'Tire tus Dudas': 'Despeja tus Dudas',
        'Perguntas <span>Frequentes</span>': 'Preguntas <span>Frecuentes</span>',
        'Não. Este é um produto 100% digital. Tú receberá os arquivos em PDF para download imediato após a confirmação do pagamento. Nada será enviado pelos correios.': 'No. Este es un producto 100% digital. Recibirás los archivos en PDF para descarga inmediata tras la confirmación del pago. Nada será enviado por correo físico.',
        'Após a confirmação do pagamento, tú receberá um e-mail com o link para download imediato de todos os 120 diseños em PDF.': 'Tras la confirmación del pago, recibirás un correo con el enlace para la descarga inmediata de los 120 diseños en PDF.',
        'Sim! Após o download, os arquivos são seus para sempre. Tú pode imprimir quantas vezes precisar, sem nenhum custo adicional.': '¡Sí! Después de descargarlos, los archivos son tuyos para siempre. Puedes imprimirlos cuantas veces necesites, sin costo adicional.',
        'Não. Os diseños podem ser impressos em qualquer impressora comum, seja jato de tinta ou laser, em papel A4 comum.': 'No. Los diseños pueden imprimirse en cualquier impresora común, de inyección de tinta o láser, en papel A4 normal.',
        'Basta imprimir o diseño, posicionar o papel carbono sobre o paño de cocina, colocar o diseño por cima e passar o lápis ou boleador sobre o desenho. É muito simples!': 'Solo imprime el diseño, coloca el papel carbón sobre el paño de cocina, pon el diseño encima y pasa un lápiz o punzón sobre el dibujo. ¡Es muy simple!',
        'Diseño pronto para imprimir e transferir para o paño de cocina': 'Diseño listo para imprimir y transferir al paño de cocina',
        'Pano de prato pintado a partir do diseño': 'Paño de cocina pintado a partir del diseño',
        'Diseño pronto para impressão e transferência': 'Diseño listo para impresión y transferencia',
        'Pano de prato pintado usando o mesmo diseño': 'Paño de cocina pintado usando el mismo diseño',
        'Diseño de pintura pronto para transferir ao tecido': 'Diseño de pintura listo para transferir a la tela',
        'Pano de prato finalizado com pintura feita a partir do diseño': 'Paño de cocina finalizado con pintura hecha a partir del diseño',
        'Pano de prato pintado a partir de um diseño pronto': 'Paño de cocina pintado a partir de un diseño listo',
        'Diseño pronto para imprimir e pintar': 'Diseño listo para imprimir y pintar',
        'Pano de prato pintado e finalizado': 'Paño de cocina pintado y finalizado',
        'Diseño de frutas para pintura em paño de cocina': 'Diseño de frutas para pintura en paño de cocina',
        'Diseño de frutas para pintura em tecido': 'Diseño de frutas para pintura en tela',
        'Diseño pronto para pintar de frutas': 'Diseño listo para pintar de frutas',
        'Diseño de café e cozinha para pintura': 'Diseño de café y cocina para pintura',
        'Diseño de cozinha para paño de cocina': 'Diseño de cocina para paño de cocina',
        'Diseño floral para pintura em tecido': 'Diseño floral para pintura en tela',
        'Diseño de flores pronto para imprimir': 'Diseño de flores listo para imprimir',
        'Diseño de animais para pintura em paño de cocina': 'Diseño de animales para pintura en paño de cocina',
        'Diseño de animais para pintura em tecido': 'Diseño de animales para pintura en tela',
        'Modelo de diseño de animais': 'Modelo de diseño de animales',
        'Diseño pronto para pintar de animais': 'Diseño listo para pintar de animales',
        'Diseño impresso em uma folha A4': 'Diseño impreso en una hoja A4',
        'Papel carbono posicionado sobre o paño de cocina': 'Papel carbón posicionado sobre el paño de cocina',
        'Diseño impresso posicionado sobre o papel carbono e o paño de cocina': 'Diseño impreso posicionado sobre el papel carbón y el paño de cocina',
        'Pessoa contornando o diseño com lápis para transferir o desenho ao tecido': 'Persona contorneando el diseño con lápiz para transferir el dibujo a la tela',
        'Capa do guia Segredos da Pintura Perfecta': 'Portada de la guía Secretos de la Pintura Perfecta',
        'Capa do Guía de Transferencia Perfecta': 'Portada de la Guía de Transferencia Perfecta',
        'Capa do Guía de Combinación de Colores': 'Portada de la Guía de Combinación de Colores',
        'Capa do guia Primeros Pasos para Vender tus Creaciones': 'Portada de la guía Primeros Pasos para Vender tus Creaciones',
        'Depoimento de cliente mostrando uma pintura de rosa em paño de cocina': 'Testimonio de cliente mostrando una pintura de rosa en paño de cocina',
        'Cliente mostrando uma pintura de limões em paño de cocina': 'Cliente mostrando una pintura de limones en paño de cocina',
        'Cliente mostrando uma pintura de xícara em paño de cocina': 'Cliente mostrando una pintura de taza en paño de cocina',
        'Depoimento de cliente mostrando uma pintura de bolo em paño de cocina': 'Testimonio de cliente mostrando una pintura de pastel en paño de cocina',
        'Cliente mostrando uma pintura de cachorro em paño de cocina': 'Cliente mostrando una pintura de perro en paño de cocina',
        'Depoimento de cliente iniciante mostrando uma pintura de bananas em paño de cocina': 'Testimonio de clienta principiante mostrando una pintura de plátanos en paño de cocina',
        'Criadora da coleção segurando um paño de cocina pintado': 'Creadora de la colección sosteniendo un paño de cocina pintado',
        'São 120 modelos prontos para imprimir,': 'Son 120 modelos listos para imprimir,',
        'transferir e pintar em seus paños de cocina.': 'transferir y pintar en tus paños de cocina.',
        'Como faço a transferência do diseño para o paño?': '¿Cómo hago la transferencia del diseño al paño?',
        'O acesso é imediato?': '¿El acceso es inmediato?',
        'Sim! Assim que o pagamento for aprovado, tú recebe o link de acesso no seu e-mail automaticamente.': '¡Sí! Tan pronto como el pago sea aprobado, recibes el enlace de acceso en tu correo electrónico automáticamente.',
        'E se eu não gostar dos diseños?': '¿Y si no me gustan los diseños?',
        'Tú tem 7 dias de garantia incondicional. Se não gostar, basta enviar um e-mail para nossa equipe que devolvemos 100% do seu dinheiro, sem burocracia.': 'Tienes 7 días de garantía incondicional. Si no te gusta, solo envía un correo a nuestro equipo y te devolveremos el 100% de tu dinero, sin burocracia.',
        'Os diseños servem para quem nunca pintou?': '¿Los diseños sirven para quien nunca ha pintado?',
        'Com certeza! Os traços são bem definidos e fáceis de acompanhar. Além disso, tú recebe uma clase en video ensinando o básico da pintura para tú começar com o pé direito.': '¡Por supuesto! Los trazos están bien definidos y son fáciles de seguir. Además, recibes una clase en video enseñando lo básico de la pintura para que empieces con el pie derecho.',
        'DISEÑOS EXCLUSIVOS': 'DISEÑOS EXCLUSIVOS',
        'Todos os direitos reservados.': 'Todos los derechos reservados.',
        'Os preços e condições de pagamento apresentados neste site podem ser alterados a qualquer momento.': 'Los precios y condiciones de pago presentados en este sitio pueden ser alterados en cualquier momento.',
        'Este site não é afiliado ao Facebook ou a qualquer entidade do Facebook.': 'Este sitio no está afiliado a Facebook ni a ninguna entidad de Facebook.',
        'PINTURA EM TECIDO DO ZERO': 'PINTURA EN TELA DESDE CERO',
        'Bono 1 - Clase en Video Pintura em Tecido do Zero:': 'Bono 1 - Clase en Video Pintura en Tela desde Cero:'
    };

    for (const [pt, es] of Object.entries(replacements)) {
        content = content.split(pt).join(es);
    }

    fs.writeFileSync('index.html', content, 'utf8');
    console.log('Replacements applied successfully.');

} catch (e) {
    console.error('Error:', e);
    process.exit(1);
}
